---
title       : Gold Stock Prices Project
subtitle    : Shiny App Presentation
author      : Eduardo Magalhaes Barbosa
job         : Coursera Developing Data Products Projects
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
license     : by-nc-sa
github      :
  user      : EduardoMagalhaes
  repo      : SlidifyPresentation
---


## Gold and Stock Price App

* This Shiny App will estimate the Stock Option price for a given Gold Mining Company.

* There will be two inputs: A date range and a A given Gold Price cost

### How it works?

* The app gathers data from internet sources for historic gold prices and stock closing values;

* For the date range supplyed, it will fitt the Stock prices in function of Gold Prices;

* There will be a chart for the fitting plot;

* Using the given Gold Target Price, the app will use the linear regression and estimate the Stock-Price;

* An Chart with historic Gold and Stock prices are showed for the selected date-range.

---


## Motion chart example

Here you can see the Stock Closing Price and Volume for three of top world Gold producers:

```{r motionchartcode, results='asis'}
# Quandl Library allows you to use online data sets
library(googleVis)
library(Quandl)
Quandl.auth("o_7e9aEakBmkPksQXFZW")  ## MyPersonal Token

## Read historic gold daily prices

Gold <- Quandl("WGC/GOLD_DAILY_USD") # Gold Price

## Read historic GOld Corp Stock prices

KGC <- Quandl("GOOG/NYSE_KGC")  # Kinross Gold Corporation
AUY <- Quandl("GOOG/NYSE_AUY")  # Yamana GOld
ABX <- Quandl("GOOG/NYSE_ABX")  # Barick Gold Corp

## Format Tables

KGC$Quote <- "KGC"
KGC$Open <- NULL
KGC$High <- NULL
KGC$Low <- NULL
KGC <- KGC[,c(4,1,2,3)]

AUY$Quote <- "AUY"
AUY$Open <- NULL
AUY$High <- NULL
AUY$Low <- NULL
AUY <- AUY[,c(4,1,2,3)]

ABX$Quote <- "ABX"
ABX$Open <- NULL
ABX$High <- NULL
ABX$Low <- NULL
ABX <- ABX[,c(4,1,2,3)]

## Merge the two datasets and clean unused collumns

Stocks <- merge(KGC, AUY, all=TRUE)
Stocks <- merge(Stocks, ABX, all=TRUE)

Stocks <- Stocks[,c(1,2,4,3)]  # Resort Stocks to easy gvismotion

## Select only one day per month

Stocks <- Stocks[as.numeric(strftime(Stocks$Date, "%m")) %in% 12 ,]
Stocks <- Stocks[as.numeric(strftime(Stocks$Date, "%d")) %in% 1 ,]

## Plot GoogleVis Chart

plot(gvisMotionChart(Stocks, "Quote", "Date", options=list(width=600, height=400)))

```

---

## Gold Fun Facts

* The last Gold closing price was `r Gold[1,2]` USD/oz on `r Gold[1,1]`.
* Compared to other metals, gold is much softer. One can beat 1 gram of gold to a 1 square meter sheet and light would shine through that sheet.
* Very few chemicals can attack gold, so that’s why it keeps it shine even when buried for 1000’s of years.
* A total of eighty-eight thousand tons of gold have been extracted from earth ever since. This means all the gold that has been dug up so far in history would, if melted, make a cube measuring approximately 25x25x25 meters.
* Gold is very rare compared with diamonds.
* Gold is one of the heaviest metals in the world. For example, it is 19,3 times as heavy as water. One cubic meter weights some 19.300 kilogram.

Source http://www.ecrresearch.com/fun-facts-about-gold


---

## Thank You!


You can see the Shiny App here: 

https://eduardomagalhaes.shinyapps.io/GoldStockPrices/

<Strong>Disclaimer</Strong>

* I would like to remind you that the data contained in this website is not necessarily real-time nor accurate. All figures (stocks, indexes, futures) and Gold prices are not provided by exchanges but rather by market makers, and so prices may not be accurate and may differ from the actual market price, meaning prices are indicative and not appropriate for trading purposes. Therefore I doesn`t bear any responsibility for any trading losses you might incur as a result of using this data .

